/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) my_quad_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[18] = {17, 1, 0, 14, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

static const casadi_real casadi_c0[4] = {2.0000000000000000e-02, -2.0000000000000000e-02, -2.0000000000000000e-02, 2.0000000000000000e-02};
static const casadi_real casadi_c1[4] = {-1.1485370000000000e-01, -1.1485370000000000e-01, 1.1717900000000001e-01, 1.1717900000000001e-01};
static const casadi_real casadi_c2[4] = {-1.5129400000000001e-01, 1.5129400000000001e-01, -1.2745300000000001e-01, 1.2745300000000001e-01};

/* my_quad_expl_vde_adj:(i0[13],i1[13],i2[4],i3[])->(o0[17x1,14nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+8, w2, *w3=w+13, *w4=w+22, *w5=w+35, *w6=w+38, *w7=w+42, w8, w9, w10, w11, w12, w13, w14, *w15=w+52, *w16=w+55, *w17=w+64, *w18=w+67, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, *w29=w+80, *w30=w+84, *w31=w+88, *w32=w+92, *w33=w+96, *w34=w+100, *w35=w+116;
  /* #0: @0 = zeros(4x1) */
  casadi_clear(w0, 4);
  /* #1: @1 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w1);
  /* #2: @2 = @1[1] */
  for (rr=(&w2), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #3: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 13, w4);
  /* #5: {@5, @6, @7, @8, @9, @10} = vertsplit(@4) */
  casadi_copy(w4, 3, w5);
  casadi_copy(w4+3, 4, w6);
  casadi_copy(w4+7, 3, w7);
  w8 = w4[10];
  w9 = w4[11];
  w10 = w4[12];
  /* #6: @11 = 0 */
  w11 = 0.;
  /* #7: @12 = 0 */
  w12 = 0.;
  /* #8: @13 = input[2][0] */
  w13 = arg[2] ? arg[2][0] : 0;
  /* #9: @14 = input[2][1] */
  w14 = arg[2] ? arg[2][1] : 0;
  /* #10: @13 = (@13+@14) */
  w13 += w14;
  /* #11: @14 = input[2][2] */
  w14 = arg[2] ? arg[2][2] : 0;
  /* #12: @13 = (@13+@14) */
  w13 += w14;
  /* #13: @14 = input[2][3] */
  w14 = arg[2] ? arg[2][3] : 0;
  /* #14: @13 = (@13+@14) */
  w13 += w14;
  /* #15: @15 = vertcat(@11, @12, @13) */
  rr=w15;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #16: @11 = 0.5069 */
  w11 = 5.0690000000000002e-01;
  /* #17: @15 = (@15/@11) */
  for (i=0, rr=w15; i<3; ++i) (*rr++) /= w11;
  /* #18: @15 = @15' */
  /* #19: @3 = mac(@7,@15,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w15+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #20: @16 = @3' */
  for (i=0, rr=w16, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #21: {@15, @17, @18} = horzsplit(@16) */
  casadi_copy(w16, 3, w15);
  casadi_copy(w16+3, 3, w17);
  casadi_copy(w16+6, 3, w18);
  /* #22: @18 = @18' */
  /* #23: {@11, @12, @13} = horzsplit(@18) */
  w11 = w18[0];
  w12 = w18[1];
  w13 = w18[2];
  /* #24: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #25: @14 = (@2*@12) */
  w14  = (w2*w12);
  /* #26: @19 = @1[2] */
  for (rr=(&w19), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #27: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #28: @20 = (@19*@11) */
  w20  = (w19*w11);
  /* #29: @14 = (@14-@20) */
  w14 -= w20;
  /* #30: @17 = @17' */
  /* #31: {@20, @21, @22} = horzsplit(@17) */
  w20 = w17[0];
  w21 = w17[1];
  w22 = w17[2];
  /* #32: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #33: @23 = (@2*@22) */
  w23  = (w2*w22);
  /* #34: @14 = (@14-@23) */
  w14 -= w23;
  /* #35: @23 = @1[3] */
  for (rr=(&w23), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #36: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #37: @24 = (@23*@20) */
  w24  = (w23*w20);
  /* #38: @14 = (@14+@24) */
  w14 += w24;
  /* #39: @15 = @15' */
  /* #40: {@24, @25, @26} = horzsplit(@15) */
  w24 = w15[0];
  w25 = w15[1];
  w26 = w15[2];
  /* #41: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #42: @27 = (@19*@26) */
  w27  = (w19*w26);
  /* #43: @14 = (@14+@27) */
  w14 += w27;
  /* #44: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #45: @27 = (@23*@25) */
  w27  = (w23*w25);
  /* #46: @14 = (@14-@27) */
  w14 -= w27;
  /* #47: (@0[0] += @14) */
  for (rr=w0+0, ss=(&w14); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #48: @14 = (2.*@2) */
  w14 = (2.* w2 );
  /* #49: @13 = (-@13) */
  w13 = (- w13 );
  /* #50: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #51: @14 = (@14*@13) */
  w14 *= w13;
  /* #52: @27 = @1[0] */
  for (rr=(&w27), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #53: @28 = (@27*@12) */
  w28  = (w27*w12);
  /* #54: @14 = (@14+@28) */
  w14 += w28;
  /* #55: @28 = (@23*@11) */
  w28  = (w23*w11);
  /* #56: @14 = (@14+@28) */
  w14 += w28;
  /* #57: @28 = (@27*@22) */
  w28  = (w27*w22);
  /* #58: @14 = (@14-@28) */
  w14 -= w28;
  /* #59: @28 = (2.*@2) */
  w28 = (2.* w2 );
  /* #60: @21 = (-@21) */
  w21 = (- w21 );
  /* #61: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #62: @28 = (@28*@21) */
  w28 *= w21;
  /* #63: @14 = (@14+@28) */
  w14 += w28;
  /* #64: @28 = (@19*@20) */
  w28  = (w19*w20);
  /* #65: @14 = (@14+@28) */
  w14 += w28;
  /* #66: @28 = (@23*@26) */
  w28  = (w23*w26);
  /* #67: @14 = (@14+@28) */
  w14 += w28;
  /* #68: @28 = (@19*@25) */
  w28  = (w19*w25);
  /* #69: @14 = (@14+@28) */
  w14 += w28;
  /* #70: (@0[1] += @14) */
  for (rr=w0+1, ss=(&w14); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #71: @14 = (@19*@12) */
  w14  = (w19*w12);
  /* #72: @28 = (@2*@11) */
  w28  = (w2*w11);
  /* #73: @14 = (@14+@28) */
  w14 += w28;
  /* #74: @28 = (@19*@22) */
  w28  = (w19*w22);
  /* #75: @14 = (@14+@28) */
  w14 += w28;
  /* #76: @28 = (2.*@23) */
  w28 = (2.* w23 );
  /* #77: @28 = (@28*@21) */
  w28 *= w21;
  /* #78: @14 = (@14+@28) */
  w14 += w28;
  /* #79: @28 = (@27*@20) */
  w28  = (w27*w20);
  /* #80: @14 = (@14+@28) */
  w14 += w28;
  /* #81: @28 = (@2*@26) */
  w28  = (w2*w26);
  /* #82: @14 = (@14+@28) */
  w14 += w28;
  /* #83: @28 = (@27*@25) */
  w28  = (w27*w25);
  /* #84: @14 = (@14-@28) */
  w14 -= w28;
  /* #85: @28 = (2.*@23) */
  w28 = (2.* w23 );
  /* #86: @24 = (-@24) */
  w24 = (- w24 );
  /* #87: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #88: @28 = (@28*@24) */
  w28 *= w24;
  /* #89: @14 = (@14+@28) */
  w14 += w28;
  /* #90: (@0[3] += @14) */
  for (rr=w0+3, ss=(&w14); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #91: @14 = (2.*@19) */
  w14 = (2.* w19 );
  /* #92: @14 = (@14*@13) */
  w14 *= w13;
  /* #93: @12 = (@23*@12) */
  w12  = (w23*w12);
  /* #94: @14 = (@14+@12) */
  w14 += w12;
  /* #95: @11 = (@27*@11) */
  w11  = (w27*w11);
  /* #96: @14 = (@14-@11) */
  w14 -= w11;
  /* #97: @22 = (@23*@22) */
  w22  = (w23*w22);
  /* #98: @14 = (@14+@22) */
  w14 += w22;
  /* #99: @20 = (@2*@20) */
  w20  = (w2*w20);
  /* #100: @14 = (@14+@20) */
  w14 += w20;
  /* #101: @26 = (@27*@26) */
  w26  = (w27*w26);
  /* #102: @14 = (@14+@26) */
  w14 += w26;
  /* #103: @25 = (@2*@25) */
  w25  = (w2*w25);
  /* #104: @14 = (@14+@25) */
  w14 += w25;
  /* #105: @25 = (2.*@19) */
  w25 = (2.* w19 );
  /* #106: @25 = (@25*@24) */
  w25 *= w24;
  /* #107: @14 = (@14+@25) */
  w14 += w25;
  /* #108: (@0[2] += @14) */
  for (rr=w0+2, ss=(&w14); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #109: @29 = zeros(4x1) */
  casadi_clear(w29, 4);
  /* #110: @14 = 0 */
  w14 = 0.;
  /* #111: @15 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w15);
  /* #112: @25 = @15[0] */
  for (rr=(&w25), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #113: @25 = (-@25) */
  w25 = (- w25 );
  /* #114: @24 = @15[1] */
  for (rr=(&w24), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #115: @24 = (-@24) */
  w24 = (- w24 );
  /* #116: @26 = @15[2] */
  for (rr=(&w26), ss=w15+2; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #117: @26 = (-@26) */
  w26 = (- w26 );
  /* #118: @30 = horzcat(@14, @25, @24, @26) */
  rr=w30;
  *rr++ = w14;
  *rr++ = w25;
  *rr++ = w24;
  *rr++ = w26;
  /* #119: @30 = @30' */
  /* #120: @14 = @15[0] */
  for (rr=(&w14), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #121: @25 = 0 */
  w25 = 0.;
  /* #122: @24 = @15[2] */
  for (rr=(&w24), ss=w15+2; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #123: @26 = @15[1] */
  for (rr=(&w26), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #124: @26 = (-@26) */
  w26 = (- w26 );
  /* #125: @31 = horzcat(@14, @25, @24, @26) */
  rr=w31;
  *rr++ = w14;
  *rr++ = w25;
  *rr++ = w24;
  *rr++ = w26;
  /* #126: @31 = @31' */
  /* #127: @14 = @15[1] */
  for (rr=(&w14), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #128: @25 = @15[2] */
  for (rr=(&w25), ss=w15+2; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #129: @25 = (-@25) */
  w25 = (- w25 );
  /* #130: @24 = 0 */
  w24 = 0.;
  /* #131: @26 = @15[0] */
  for (rr=(&w26), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #132: @32 = horzcat(@14, @25, @24, @26) */
  rr=w32;
  *rr++ = w14;
  *rr++ = w25;
  *rr++ = w24;
  *rr++ = w26;
  /* #133: @32 = @32' */
  /* #134: @14 = @15[2] */
  for (rr=(&w14), ss=w15+2; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #135: @25 = @15[1] */
  for (rr=(&w25), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #136: @24 = @15[0] */
  for (rr=(&w24), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #137: @24 = (-@24) */
  w24 = (- w24 );
  /* #138: @26 = 0 */
  w26 = 0.;
  /* #139: @33 = horzcat(@14, @25, @24, @26) */
  rr=w33;
  *rr++ = w14;
  *rr++ = w25;
  *rr++ = w24;
  *rr++ = w26;
  /* #140: @33 = @33' */
  /* #141: @34 = horzcat(@30, @31, @32, @33) */
  rr=w34;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<4; ++i) *rr++ = *cs++;
  /* #142: @14 = 0.5 */
  w14 = 5.0000000000000000e-01;
  /* #143: @6 = (@14*@6) */
  for (i=0, rr=w6, cs=w6; i<4; ++i) (*rr++)  = (w14*(*cs++));
  /* #144: @29 = mac(@34,@6,@29) */
  for (i=0, rr=w29; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w34+j, tt=w6+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #145: @0 = (@0+@29) */
  for (i=0, rr=w0, cs=w29; i<4; ++i) (*rr++) += (*cs++);
  /* #146: output[0][0] = @0 */
  casadi_copy(w0, 4, res[0]);
  /* #147: output[0][1] = @5 */
  if (res[0]) casadi_copy(w5, 3, res[0]+4);
  /* #148: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #149: @14 = -0.00144857 */
  w14 = -1.4485650000000002e-03;
  /* #150: @25 = @15[0] */
  for (rr=(&w25), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #151: @25 = (@14*@25) */
  w25  = (w14*w25);
  /* #152: @24 = 357.188 */
  w24 = 3.5718750558105478e+02;
  /* #153: @24 = (@24*@10) */
  w24 *= w10;
  /* #154: @25 = (@25*@24) */
  w25 *= w24;
  /* #155: (@5[1] += @25) */
  for (rr=w5+1, ss=(&w25); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #156: @25 = @15[1] */
  for (rr=(&w25), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #157: @25 = (@25*@24) */
  w25 *= w24;
  /* #158: @14 = (@14*@25) */
  w14 *= w25;
  /* #159: (@5[0] += @14) */
  for (rr=w5+0, ss=(&w14); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #160: @14 = 0.0018858 */
  w14 = 1.8857950000000000e-03;
  /* #161: @25 = @15[2] */
  for (rr=(&w25), ss=w15+2; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #162: @25 = (@14*@25) */
  w25  = (w14*w25);
  /* #163: @10 = 423.295 */
  w10 = 4.2329475707113892e+02;
  /* #164: @10 = (@10*@9) */
  w10 *= w9;
  /* #165: @25 = (@25*@10) */
  w25 *= w10;
  /* #166: (@5[0] += @25) */
  for (rr=w5+0, ss=(&w25); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #167: @25 = @15[0] */
  for (rr=(&w25), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #168: @25 = (@25*@10) */
  w25 *= w10;
  /* #169: @14 = (@14*@25) */
  w14 *= w25;
  /* #170: (@5[2] += @14) */
  for (rr=w5+2, ss=(&w14); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #171: @14 = -0.00043723 */
  w14 = -4.3722999999999982e-04;
  /* #172: @25 = @15[1] */
  for (rr=(&w25), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #173: @25 = (@14*@25) */
  w25  = (w14*w25);
  /* #174: @9 = 1094.27 */
  w9 = 1.0942655016386625e+03;
  /* #175: @9 = (@9*@8) */
  w9 *= w8;
  /* #176: @25 = (@25*@9) */
  w25 *= w9;
  /* #177: (@5[2] += @25) */
  for (rr=w5+2, ss=(&w25); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #178: @25 = @15[2] */
  for (rr=(&w25), ss=w15+2; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #179: @25 = (@25*@9) */
  w25 *= w9;
  /* #180: @14 = (@14*@25) */
  w14 *= w25;
  /* #181: (@5[1] += @14) */
  for (rr=w5+1, ss=(&w14); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #182: @34 = zeros(4x4) */
  casadi_clear(w34, 16);
  /* #183: @1 = @1' */
  /* #184: @34 = mac(@6,@1,@34) */
  for (i=0, rr=w34; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w6+j, tt=w1+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #185: @35 = @34' */
  for (i=0, rr=w35, cs=w34; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #186: {@6, @1, @0, @29} = horzsplit(@35) */
  casadi_copy(w35, 4, w6);
  casadi_copy(w35+4, 4, w1);
  casadi_copy(w35+8, 4, w0);
  casadi_copy(w35+12, 4, w29);
  /* #187: @29 = @29' */
  /* #188: {@14, @25, @8, NULL} = horzsplit(@29) */
  w14 = w29[0];
  w25 = w29[1];
  w8 = w29[2];
  /* #189: @8 = (-@8) */
  w8 = (- w8 );
  /* #190: (@5[0] += @8) */
  for (rr=w5+0, ss=(&w8); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #191: (@5[1] += @25) */
  for (rr=w5+1, ss=(&w25); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #192: (@5[2] += @14) */
  for (rr=w5+2, ss=(&w14); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #193: @0 = @0' */
  /* #194: {@14, @25, NULL, @8} = horzsplit(@0) */
  w14 = w0[0];
  w25 = w0[1];
  w8 = w0[3];
  /* #195: (@5[0] += @8) */
  for (rr=w5+0, ss=(&w8); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #196: @25 = (-@25) */
  w25 = (- w25 );
  /* #197: (@5[2] += @25) */
  for (rr=w5+2, ss=(&w25); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #198: (@5[1] += @14) */
  for (rr=w5+1, ss=(&w14); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #199: @1 = @1' */
  /* #200: {@14, NULL, @25, @8} = horzsplit(@1) */
  w14 = w1[0];
  w25 = w1[2];
  w8 = w1[3];
  /* #201: @8 = (-@8) */
  w8 = (- w8 );
  /* #202: (@5[1] += @8) */
  for (rr=w5+1, ss=(&w8); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #203: (@5[2] += @25) */
  for (rr=w5+2, ss=(&w25); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #204: (@5[0] += @14) */
  for (rr=w5+0, ss=(&w14); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #205: @6 = @6' */
  /* #206: {NULL, @14, @25, @8} = horzsplit(@6) */
  w14 = w6[1];
  w25 = w6[2];
  w8 = w6[3];
  /* #207: @8 = (-@8) */
  w8 = (- w8 );
  /* #208: (@5[2] += @8) */
  for (rr=w5+2, ss=(&w8); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #209: @25 = (-@25) */
  w25 = (- w25 );
  /* #210: (@5[1] += @25) */
  for (rr=w5+1, ss=(&w25); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #211: @14 = (-@14) */
  w14 = (- w14 );
  /* #212: (@5[0] += @14) */
  for (rr=w5+0, ss=(&w14); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #213: output[0][2] = @5 */
  if (res[0]) casadi_copy(w5, 3, res[0]+7);
  /* #214: @6 = [0.02, -0.02, -0.02, 0.02] */
  casadi_copy(casadi_c0, 4, w6);
  /* #215: @6 = @6' */
  /* #216: @6 = (@24*@6) */
  for (i=0, rr=w6, cs=w6; i<4; ++i) (*rr++)  = (w24*(*cs++));
  /* #217: @6 = @6' */
  /* #218: @1 = [-0.114854, -0.114854, 0.117179, 0.117179] */
  casadi_copy(casadi_c1, 4, w1);
  /* #219: @1 = @1' */
  /* #220: @1 = (@10*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w10*(*cs++));
  /* #221: @1 = @1' */
  /* #222: @6 = (@6+@1) */
  for (i=0, rr=w6, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #223: @1 = [-0.151294, 0.151294, -0.127453, 0.127453] */
  casadi_copy(casadi_c2, 4, w1);
  /* #224: @1 = @1' */
  /* #225: @1 = (@9*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w9*(*cs++));
  /* #226: @1 = @1' */
  /* #227: @6 = (@6+@1) */
  for (i=0, rr=w6, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #228: {@9, @10, @24, @14} = vertsplit(@6) */
  w9 = w6[0];
  w10 = w6[1];
  w24 = w6[2];
  w14 = w6[3];
  /* #229: @25 = 1.97278 */
  w25 = 1.9727756954034326e+00;
  /* #230: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #231: @8 = 1 */
  w8 = 1.;
  /* #232: @26 = sq(@19) */
  w26 = casadi_sq( w19 );
  /* #233: @20 = sq(@23) */
  w20 = casadi_sq( w23 );
  /* #234: @26 = (@26+@20) */
  w26 += w20;
  /* #235: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #236: @8 = (@8-@26) */
  w8 -= w26;
  /* #237: @26 = (@2*@19) */
  w26  = (w2*w19);
  /* #238: @20 = (@27*@23) */
  w20  = (w27*w23);
  /* #239: @26 = (@26-@20) */
  w26 -= w20;
  /* #240: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #241: @20 = (@2*@23) */
  w20  = (w2*w23);
  /* #242: @22 = (@27*@19) */
  w22  = (w27*w19);
  /* #243: @20 = (@20+@22) */
  w20 += w22;
  /* #244: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #245: @15 = horzcat(@8, @26, @20) */
  rr=w15;
  *rr++ = w8;
  *rr++ = w26;
  *rr++ = w20;
  /* #246: @15 = @15' */
  /* #247: @8 = (@2*@19) */
  w8  = (w2*w19);
  /* #248: @26 = (@27*@23) */
  w26  = (w27*w23);
  /* #249: @8 = (@8+@26) */
  w8 += w26;
  /* #250: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #251: @26 = 1 */
  w26 = 1.;
  /* #252: @20 = sq(@2) */
  w20 = casadi_sq( w2 );
  /* #253: @22 = sq(@23) */
  w22 = casadi_sq( w23 );
  /* #254: @20 = (@20+@22) */
  w20 += w22;
  /* #255: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #256: @26 = (@26-@20) */
  w26 -= w20;
  /* #257: @20 = (@19*@23) */
  w20  = (w19*w23);
  /* #258: @22 = (@27*@2) */
  w22  = (w27*w2);
  /* #259: @20 = (@20-@22) */
  w20 -= w22;
  /* #260: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #261: @17 = horzcat(@8, @26, @20) */
  rr=w17;
  *rr++ = w8;
  *rr++ = w26;
  *rr++ = w20;
  /* #262: @17 = @17' */
  /* #263: @8 = (@2*@23) */
  w8  = (w2*w23);
  /* #264: @26 = (@27*@19) */
  w26  = (w27*w19);
  /* #265: @8 = (@8-@26) */
  w8 -= w26;
  /* #266: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #267: @23 = (@19*@23) */
  w23  = (w19*w23);
  /* #268: @27 = (@27*@2) */
  w27 *= w2;
  /* #269: @23 = (@23+@27) */
  w23 += w27;
  /* #270: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #271: @27 = 1 */
  w27 = 1.;
  /* #272: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #273: @19 = sq(@19) */
  w19 = casadi_sq( w19 );
  /* #274: @2 = (@2+@19) */
  w2 += w19;
  /* #275: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #276: @27 = (@27-@2) */
  w27 -= w2;
  /* #277: @18 = horzcat(@8, @23, @27) */
  rr=w18;
  *rr++ = w8;
  *rr++ = w23;
  *rr++ = w27;
  /* #278: @18 = @18' */
  /* #279: @16 = horzcat(@15, @17, @18) */
  rr=w16;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  /* #280: @5 = mac(@16,@7,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w7+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #281: @5 = (@25*@5) */
  for (i=0, rr=w5, cs=w5; i<3; ++i) (*rr++)  = (w25*(*cs++));
  /* #282: {NULL, NULL, @25} = vertsplit(@5) */
  w25 = w5[2];
  /* #283: @9 = (@9+@25) */
  w9 += w25;
  /* #284: output[0][3] = @9 */
  if (res[0]) res[0][10] = w9;
  /* #285: @10 = (@10+@25) */
  w10 += w25;
  /* #286: output[0][4] = @10 */
  if (res[0]) res[0][11] = w10;
  /* #287: @24 = (@24+@25) */
  w24 += w25;
  /* #288: output[0][5] = @24 */
  if (res[0]) res[0][12] = w24;
  /* #289: @14 = (@14+@25) */
  w14 += w25;
  /* #290: output[0][6] = @14 */
  if (res[0]) res[0][13] = w14;
  return 0;
}

CASADI_SYMBOL_EXPORT int my_quad_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int my_quad_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int my_quad_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void my_quad_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int my_quad_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void my_quad_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void my_quad_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void my_quad_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int my_quad_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int my_quad_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real my_quad_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* my_quad_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* my_quad_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* my_quad_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* my_quad_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int my_quad_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 132;
  return 0;
}

CASADI_SYMBOL_EXPORT int my_quad_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 132*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
